"""
Maze Runner Algorithm using Left-Hand Wall Following

Uses two ultrasonic sensors:
- Front sensor (GP6/GP7): read_distance() - detects walls ahead
- Left sensor (GP4/GP5): read_distance_2() - detects left wall

Strategy: Follow the left wall. Keep a consistent distance from it.
If front is blocked, turn right. If left opens up, turn left to follow it.
"""

from aidriver import AIDriver, hold_state
import aidriver

# Enable debug output
aidriver.DEBUG_AIDRIVER = True

# === TUNING PARAMETERS ===
WALL_THRESHOLD = 150       # mm - closer than this = wall detected
FRONT_STOP_DISTANCE = 100  # mm - stop/turn when front wall this close
TARGET_LEFT_DISTANCE = 120 # mm - ideal distance from left wall
LEFT_TOLERANCE = 30        # mm - acceptable deviation from target

DRIVE_SPEED = 180          # Base forward speed (0-255)
TURN_SPEED = 160           # Speed for turning
ADJUST_SPEED = 40          # Speed delta for course corrections


def run_maze():
    """Main maze-running loop using left-hand wall following."""
        
            print("Initializing maze runner...")
                robot = AIDriver()
                    
                        print("Starting maze run in 3 seconds...")
                            print("Place robot with left wall nearby, front facing down corridor")
                                hold_state(3)
                                    
                                        print("Running maze...")
                                            
                                                while True:
                                                        # Read both sensors
                                                                front_dist = robot.read_distance()
                                                                        left_dist = robot.read_distance_2()
                                                                                
                                                                                        # Handle sensor errors (-1 = no reading)
                                                                                                front_clear = front_dist == -1 or front_dist > FRONT_STOP_DISTANCE
                                                                                                        left_wall_present = left_dist != -1 and left_dist < WALL_THRESHOLD
                                                                                                                
                                                                                                                        print(f"Front: {front_dist}mm, Left: {left_dist}mm")
                                                                                                                                
                                                                                                                                        # === DECISION LOGIC ===
                                                                                                                                                
                                                                                                                                                        # CASE 1: Front wall detected - must turn right
                                                                                                                                                                if not front_clear:
                                                                                                                                                                            print("Front blocked - turning right")
                                                                                                                                                                                        robot.brake()
                                                                                                                                                                                                    hold_state(0.2)
                                                                                                                                                                                                                robot.rotate_right(TURN_SPEED)
                                                                                                                                                                                                                            hold_state(0.4)  # Turn ~90 degrees
                                                                                                                                                                                                                                        robot.brake()
                                                                                                                                                                                                                                                    hold_state(0.1)
                                                                                                                                                                                                                                                                continue
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                # CASE 2: No left wall - opening detected, turn left to follow
                                                                                                                                                                                                                                                                                        if not left_wall_present:
                                                                                                                                                                                                                                                                                                    print("Left opening - turning left")
                                                                                                                                                                                                                                                                                                                # Drive forward a bit to clear the corner
                                                                                                                                                                                                                                                                                                                            robot.drive_forward(DRIVE_SPEED, DRIVE_SPEED)
                                                                                                                                                                                                                                                                                                                                        hold_state(0.3)
                                                                                                                                                                                                                                                                                                                                                    robot.brake()
                                                                                                                                                                                                                                                                                                                                                                hold_state(0.1)
                                                                                                                                                                                                                                                                                                                                                                            # Turn left
                                                                                                                                                                                                                                                                                                                                                                                        robot.rotate_left(TURN_SPEED)
                                                                                                                                                                                                                                                                                                                                                                                                    hold_state(0.4)  # Turn ~90 degrees
                                                                                                                                                                                                                                                                                                                                                                                                                robot.brake()
                                                                                                                                                                                                                                                                                                                                                                                                                            hold_state(0.1)
                                                                                                                                                                                                                                                                                                                                                                                                                                        # Drive forward to enter the opening
                                                                                                                                                                                                                                                                                                                                                                                                                                                    robot.drive_forward(DRIVE_SPEED, DRIVE_SPEED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                hold_state(0.3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            robot.brake()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hold_state(0.1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # CASE 3: Left wall present, front clear - follow the wall
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Adjust steering to maintain target distance from left wall
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            error = left_dist - TARGET_LEFT_DISTANCE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if abs(error) < LEFT_TOLERANCE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # On track - drive straight
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    robot.drive_forward(DRIVE_SPEED, DRIVE_SPEED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif error > 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Too far from left wall - veer left (slow right wheel)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    robot.drive_forward(DRIVE_SPEED - ADJUST_SPEED, DRIVE_SPEED + ADJUST_SPEED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Too close to left wall - veer right (slow left wheel)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    robot.drive_forward(DRIVE_SPEED + ADJUST_SPEED, DRIVE_SPEED - ADJUST_SPEED)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    hold_state(0.1)  # Small delay between sensor reads
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Entry point with error handling."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    run_maze()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except KeyboardInterrupt:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\nStopped by user")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Try to stop the robot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            robot = AIDriver()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        robot.brake()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Maze runner stopped")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """